### ISSUE TITLE
Add crontab support to be able to pack the Data.fs

### ISSUE THREAD

**Issue by erral** [plone/plone-zeo#3]
Is it worth to add crontab support to this image to be able to support packing the ZODB?

EEA's base Plone 5 image does it in [an entrypoint.sh file](https://github.com/eea/eea.docker.plone/blob/master/src/docker/common-entrypoint.sh)

I don't know if something similar could be done here (where? in start-zeo.sh?) or whether it makes sense at all... perhaps it could be done in some other way... any hint on this?

**Comment by fredvd** [comment]
@erral I jiusr spotted this issue again, totally forgot about it.  This doesn’t need to be added  to the zeoserver. It’s included in the zeoclient. At least for the plone-backend images:  you can do something like this if it is relstorage based. But zeobased should work the same, the client can trigger a pack. Or?


iif you define the service with docker swarm and you use the swarm-cromjob container, it is 2 extra labels to schedule the zeopack


```

pack:
    image: plone/plone-backend:6.0.13
    environment:
      RELSTORAGE_DSN: "dbname='${DB_NAME:-mydb}' user='${DB_USER:-mydb}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-defaulchamgeme}' port='${DB_PORT:-5432}'"
    command: bin/zodbpack -d 3 /zodbpack_conf
    healthcheck:
      disable: true
    deploy:
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 1 * * Sun"
      restart_policy:
        condition: none
    configs:
      - zodbpack_conf
 ```
